site_name: Brinjal Documentation
site_description: Generic task management system built with FastAPI and asyncio
site_author: Your Name
site_url: https://your-domain.com/brinjal

repo_name: sg-s/brinjal
repo_url: https://github.com/sg-s/brinjal
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Task Development: task-development.md
  - API Reference: api-reference.md
  - Web Component: web-component.md
  - Integration Guide: integration.md
  - Examples: examples.md
  - Development: development.md

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      anchorlink: true
      permalink: true
      title: On this page

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sg-s/brinjal


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
